"""razorpay_fields

Revision ID: a3ed10cfd01b
Revises: 2b7a1a3a1c9d
Create Date: 2026-03-18 19:00:14.263420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ed10cfd01b'
down_revision = '2b7a1a3a1c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_payments_razorpay_order_id', ['razorpay_order_id'])
        batch_op.create_unique_constraint('uq_payments_razorpay_payment_id', ['razorpay_payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payments_razorpay_order_id', type_='unique')
        batch_op.drop_constraint('uq_payments_razorpay_payment_id', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('event_id')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('method')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('razorpay_payment_id')

    op.create_table('_alembic_tmp_menu_categories',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('restaurant_id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
